application: proxytweet
version: 1
runtime: python
api_version: 1

handlers:
- url: /poll
  script: main.py
- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml